# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/ece485_finalproject_stage2.cache/wt [current_project]
set_property parent.project_path C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/ece485_finalproject_stage2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/ece485_finalproject_stage2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/alu.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/alu_control.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/control_unit.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/data_mem.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/immediate_generator.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/instr_mem.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/pc.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/reg_file.vhdl
  C:/Users/george.york/Documents/ECE485_code/ece485_finalproject_stage2/riscv_pipeline.vhdl
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top riscv_pipeline -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_pipeline.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_pipeline_utilization_synth.rpt -pb riscv_pipeline_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
